FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    git \
    python3-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.backend.txt .

# Install CPU PyTorch first to prevent timeouts
RUN pip install --no-cache-dir --default-timeout=1000 torch --index-url https://download.pytorch.org/whl/cpu

# Install RAG and Guardrails dependencies
RUN pip install --no-cache-dir --default-timeout=1000 --upgrade pip setuptools wheel && \
    pip install --no-cache-dir --default-timeout=1000 -r requirements.backend.txt

COPY backend/ ./backend/
COPY "HR_Document.pdf" ./backend/

WORKDIR /app/backend
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]