FROM python:3.10-slim

WORKDIR /app

COPY requirements.frontend.txt .

RUN pip install --no-cache-dir --default-timeout=1000 -r requirements.frontend.txt

COPY app.py .

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]